# Generated by Django 5.2.8 on 2025-11-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="jury_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="jury_events",
                to="users.user",
                verbose_name="Члены жюри",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_admin": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_events",
                to="users.user",
                verbose_name="Менеджер мероприятия",
            ),
        ),
    ]
