# Generated by Django 5.2.8 on 2025-11-22 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_jury_members_event_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="jury_members",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_admin": False},
                related_name="jury_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Члены жюри",
            ),
        ),
    ]
