# Generated by Django 5.2.8 on 2025-11-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "vk_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="VK ID"
                    ),
                ),
                (
                    "tg_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Учебное заведение / организация",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Администратор"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="EventUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField(verbose_name="ID мероприятия")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Менеджер"),
                            ("jury", "Член жюри"),
                            ("participant", "Участник"),
                        ],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_roles",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя в мероприятии",
                "verbose_name_plural": "Роли пользователей в мероприятиях",
                "unique_together": {("user", "event_id", "role")},
            },
        ),
    ]
